name=RadioLIFT
version=1.0.1
author=José Silva
maintainer=José Silva
sentence=RadioLIFT library
paragraph=Radio comms for the LIFT project
category=Communication
url=https://github.com/jcsilva7/IMECX-LIFT
architectures=avr